/**
 * The specs view vocabulary, in one place: the category order the
 * index presents, their labels, and the grouping both specs routes
 * share. The categories themselves come from spec frontmatter
 * (generated by scripts/lib/specs-converter.mjs from the `:product:`
 * attribute, with number-prefix fallbacks).
 */

export const SPEC_CATEGORY_ORDER = [
  'index',
  'architecture',
  'modes',
  'threshold',
  'transparency',
  'pki',
  'keyless',
  'privacy',
  'verify',
  'security',
] as const;

export const SPEC_CATEGORY_LABELS: Record<string, string> = {
  index: 'Product index',
  architecture: 'Architecture',
  modes: 'Deployment modes',
  threshold: 'Threshold',
  transparency: 'Transparency',
  pki: 'PKI',
  keyless: 'Keyless',
  privacy: 'Privacy',
  verify: 'Verify',
  security: 'Security',
  spec: 'Specifications',
};

export interface SpecLike {
  data: { category?: string; upstream_path: string };
}

export interface SpecCategoryGroup<T> {
  category: string;
  label: string;
  specs: T[];
}

function categoryRank(category: string): number {
  const i = (SPEC_CATEGORY_ORDER as readonly string[]).indexOf(category);
  return i === -1 ? SPEC_CATEGORY_ORDER.length : i;
}

/**
 * Group specs by category in presentation order (known categories in
 * SPEC_CATEGORY_ORDER, then unknown categories alphabetically).
 * Within a group, specs keep upstream_path order.
 */
export function groupSpecsByCategory<T extends SpecLike>(specs: T[]): SpecCategoryGroup<T>[] {
  const sorted = [...specs].sort((a, b) =>
    a.data.upstream_path.localeCompare(b.data.upstream_path),
  );
  const byCategory = new Map<string, T[]>();
  for (const s of sorted) {
    const cat = s.data.category || 'spec';
    if (!byCategory.has(cat)) byCategory.set(cat, []);
    byCategory.get(cat)!.push(s);
  }
  return [...byCategory.entries()]
    .map(([category, group]) => ({
      category,
      label: SPEC_CATEGORY_LABELS[category] ?? category,
      specs: group,
    }))
    .sort((a, b) => categoryRank(a.category) - categoryRank(b.category) || a.category.localeCompare(b.category));
}
